### PR TITLE
[WIP] First Working Prototype

### PR DESCRIPTION
**Pull request by VoxelMC**

### CODE REVIEW

**Review by SatanshuMishra — APPROVED** [review]
Looks good. Implementing Auth (Sign Up, Sign in and Sign out) is a good addition.

**Comment by VoxelMC** [comment]
Todo Still:

- Add item to database
- Delete mode
- Delete item from database

**Comment by VoxelMC** [comment]
> Todo Still:
> 
> * Add item to database
> * Delete mode
> * Delete item from database

Done!

QoL Improvements will be:

```[tasklist]
### My tasks
- [ ] Add a save state to reload the correct tab after reloading the page
- [ ] Make the pages manageable - aesthetics-wise
```

**Comment by VoxelMC** [comment]
I am merging this for now, but the todos in https://github.com/sm-ts/list-thing/pull/1#issuecomment-1882007008 still stand!
@SatanshuMishra

**Pull request merged**
